name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3    
    - name: Build Svelte Docker image
      run: docker build svelte-project/ --file svelte-project/Dockerfile --tag redtea89/blog-svelte:amd
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push redtea89/blog-svelte:amd
